### ISSUE TITLE
In-line code doesn't have line break

### ISSUE THREAD

**Issue by coder-with-a-bushido** [satnaing/astro-paper#100]
I recently forked astro-paper for building a personal blog site and man, it's the best thing. I really loved how the code was structured and was able to pull off something cool by tweaking some things. That aside, I just noticed a bug where if you have a long word without a break as `in-line code` (yes, the one with backticks), it doesn't break naturally to next line in mobile view. This makes the other components wrap under less width making the page look weird.

![image](https://github.com/satnaing/astro-paper/assets/62273306/b3b163af-8a70-46a6-bcaa-064c9aa331ef)

**Comment by coder-with-a-bushido** [comment]
## Some more info:

I ran `npm run build` and checked the html output for the blog:
```
<p><code>import 'package:action_process_text/action_process_text.dart';</code></p>
```
So, I went ahead and tried adding [hyphenapoly remark plugin](https://eatmon.co/blog/suggest-line-breaks-markdown/) with the following css:
```
.prose p {
    @apply prose-code:hyphens-manual prose-code:text-justify;
  }
```
  which didn't work, so tried this:
```
  .prose p code {
    @apply hyphens-manual text-justify;
  }
  ```
  Even that didn't work.
  
  ## Steps to reproduce
  Try pasting the following into a blog markdown file and check that page in mobile view:
  `import 'package:action_process_text/action_process_text.dart';`

**Comment by Xkonti** [comment]
Hmm. This might be the case where the inline code is a bit misused. The inline code is intended to be used as just a word or two that you mention mid-sentence. Like a `variableName` or `alpha != omega`. In your case it's a whole line of code and therefore I would suggest using a code block instead.

**Comment by satnaing** [comment]
Hello @coder-with-a-bushido,

Just like @Xkonti said above, you should use inline code for only one or two words. If you have a long code block, just like `import` line in your example, you should use [Fenced code blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks).

So, instead of using \` import 'package:something'\`, you can use 

\```
import 'package:something' 
\```

Here's the result.

Old code
`import 'package:action_process_text/action_process_text.dart';`

New code
```js
import 'package:action_process_text/action_process_text.dart';
```

**Comment by VGalaxies** [comment]
> ## Some more info:
> I ran `npm run build` and checked the html output for the blog:
> 
> ```
> <p><code>import 'package:action_process_text/action_process_text.dart';</code></p>
> ```
> 
> So, I went ahead and tried adding [hyphenapoly remark plugin](https://eatmon.co/blog/suggest-line-breaks-markdown/) with the following css:
> 
> ```
> .prose p {
>     @apply prose-code:hyphens-manual prose-code:text-justify;
>   }
> ```
> 
> which didn't work, so tried this:
> 
> ```
>   .prose p code {
>     @apply hyphens-manual text-justify;
>   }
> ```
> 
> Even that didn't work.
> 
> ## Steps to reproduce
> Try pasting the following into a blog markdown file and check that page in mobile view: `import 'package:action_process_text/action_process_text.dart';` OR Try using this [blog markdown file](https://github.com/coder-with-a-bushido/coder-with-a-bushido/blob/main/src/content/blog/action-process-text.md?rgh-link-date=2023-07-30T16%3A22%3A59Z) directly.

@coder-with-a-bushido, maybe can use

```css
.prose code {
  @apply break-all;
}
```
but I'm not sure if there will be any side effects
