### ISSUE TITLE
Feature Improvements: Allow for more flexible formatting on the frontmatter of content/blog documents.

### ISSUE THREAD

**Issue by noidwasavailable** [satnaing/astro-paper#103]
Similarly to issue #88, build breaks on having a `?` in the title of a post as well.

Example:
![Build Error](https://i.imgur.com/VeQoLLt.png)

Not the same error, but also on having quoted text (any of `''`, `""`, backticks) on the description of a post, dev server breaks with errors such as [this one](https://docs.astro.build/en/reference/errors/markdown-frontmatter-parse-error/).

Parsing the titles and descriptions more intelligently would help authors write more versatile titles.

Also, currently, markdown formatting is not supported in the frontmatter title or description, which would be a nice added functionality.

**Comment by satnaing** [comment]
This bug is going to be solved in AstroPaper v3.
