### ISSUE TITLE
Figma file

### ISSUE THREAD

**Issue by ajsb85** [satnaing/astro-paper#104]
Dear @satnaing 
Could you please share to the community the design resources on Figma?
Thank you.

**Comment by satnaing** [comment]
Hello @ajsb85 

I just designed this inside my "combined" Figma file 😬. Which means drew this design along with my portfolio website Figma file. 
TBH, I've never imagined someone would be interested in this site's design 😆.

I'll try to separate this design into a file and share it in the future. 

Thanks! ✌🏻

**Comment by Yasir-Khan22** [comment]
@satnaing 
Any plan for sharing figma design file to community?

**Comment by satnaing** [comment]
Hello @ajsb85 and @Yasir-Khan22,

I've published the design resource for AstroPaper on the Figma community. I've updated my design with `auto layouts`, `variables`, and properly reorganized them.

I hope you like it, and feedback and suggestions are welcomed as well.

Thanks.
