### ISSUE TITLE
Debug option

### ISSUE THREAD

**Issue by gangesh** [satnaing/astro-paper#108]
hi, I am trying to connect CMS REST API. 
I tried usual JS debugging for checking response returned, nothing shows up. 
Any suggestions?

**Comment by satnaing** [comment]
Hello @gangesh 
Sorry for my late response.

Without knowing the exact context, it is hard to suggest what went wrong. But, here's my general idea for fixing that. 
How about checking the network tab in the Chrome tab? This is what I usually do for inspecting network responses.

Please do let me know if you've solved this issue.
