### ISSUE TITLE
IBM Plex Sans font have issue with tags 

### ISSUE THREAD

**Issue by muneib** [satnaing/astro-paper#109]
When I use IBM Plex Sans font the tags looks like this
![Screenshot from 2023-08-24 13-10-01](https://github.com/satnaing/astro-paper/assets/73744785/3003da90-237d-4e7a-a50d-869219e8c3d5)
```css
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Roboto:wght@100&display=swap" rel="stylesheet">
```
Any help?

**Comment by satnaing** [comment]
Hello @muneib 

When I update the IBM Plex Sans font, I don't see anything wrong.
![image](https://github.com/satnaing/astro-paper/assets/53733092/7bb8ff33-4789-47aa-8d1b-ddee4752d961)

But just in case you're still facing this issue, you can fix like this

```html
<li
  class={`inline-block ${
    size === "sm" ? "my-1 underline-offset-4" : "my-3 mx-1 underline-offset-8"
  }`}
>
  <a
    href={`/tags/${name.toLowerCase()}`}
    transition:name={name.toLowerCase()}
    class={`${size === "sm" ? "text-sm" : "text-lg"} pr-2 group`}
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class={`${size === "sm" ? " scale-75" : "scale-110"}`}
      ><path
        d="M16.018 3.815 15.232 8h-4.966l.716-3.815-1.964-.37L8.232 8H4v2h3.857l-.751 4H3v2h3.731l-.714 3.805 1.965.369L8.766 16h4.966l-.714 3.805 1.965.369.783-4.174H20v-2h-3.859l.751-4H21V8h-3.733l.716-3.815-1.965-.37zM14.106 14H9.141l.751-4h4.966l-.752 4z"
      ></path>
    </svg>
    <!-- &nbsp;<span>{name.toLowerCase()}</span> --> // old code 
    &nbsp;&nbsp;<span>{name.toLowerCase()}</span> // add more '&nbsp;' here
  </a>
</li>
```

Hope this helps! 
I'll close this issue for now. But if you still have the problem, do let me know and you can reopen this.

**Comment by satnaing** [comment]
Hello @muneib 

When I update the IBM Plex Sans font, I don't see anything wrong.
![image](https://github.com/satnaing/astro-paper/assets/53733092/7bb8ff33-4789-47aa-8d1b-ddee4752d961)

But just in case you're still facing this issue, you can fix like this

```html
<li
  class={`inline-block ${
    size === "sm" ? "my-1 underline-offset-4" : "my-3 mx-1 underline-offset-8"
  }`}
>
  <a
    href={`/tags/${name.toLowerCase()}`}
    transition:name={name.toLowerCase()}
    class={`${size === "sm" ? "text-sm" : "text-lg"} pr-2 group`}
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class={`${size === "sm" ? " scale-75" : "scale-110"}`}
      ><path
        d="M16.018 3.815 15.232 8h-4.966l.716-3.815-1.964-.37L8.232 8H4v2h3.857l-.751 4H3v2h3.731l-.714 3.805 1.965.369L8.766 16h4.966l-.714 3.805 1.965.369.783-4.174H20v-2h-3.859l.751-4H21V8h-3.733l.716-3.815-1.965-.37zM14.106 14H9.141l.751-4h4.966l-.752 4z"
      ></path>
    </svg>
    <!-- &nbsp;<span>{name.toLowerCase()}</span> --> // old code 
    &nbsp;&nbsp;<span>{name.toLowerCase()}</span> // add more '&nbsp;' here
  </a>
</li>
```

Hope this helps! 
I'll close this issue for now. But if you still have the problem, do let me know and you can reopen this.

**Comment by trevoragilbert** [comment]
@satnaing I'm working on resolving this with a different font, but wanted to let you know that this issue is still there. 
<img width="362" alt="Screenshot 2023-12-15 at 2 57 15 PM" src="https://github.com/satnaing/astro-paper/assets/642848/62d24380-6dba-4d15-a0bd-981f366ad06d">
<img width="160" alt="Screenshot 2023-12-15 at 2 57 11 PM" src="https://github.com/satnaing/astro-paper/assets/642848/20a46e6c-d3ab-4937-81d0-0e6ca93a392f">
