### ISSUE TITLE
Suggestion: Modifications to the scripts in package.json are necessary for Windows compatibility.

### ISSUE THREAD

**Issue by gyunseo** [satnaing/astro-paper#113]
`npm run dev` contains the bash(or zsh, fish etc) `&` operator, which is not compatible with Windows Powershell. It would be good to add the `concurrently` package to dev dependencies and make the following changes.

```json
"dev": "concurrently --raw --kill-others \"astro check --watch\" \"astro dev\"",
```

**Comment by satnaing** [comment]
So Windows Powershell users can only run the `dev` with your changes? Didn't know that. 
BTW, what else did you encounter running AstroPaper?

**Comment by satnaing** [comment]
So, currently, I'm thinking of two options.

1) Add a section in `docs` and `README` for Windows PowerShell users, with a warning about running the script, and an explanation of what should be done to run the project.
2) Add [concurrently package](https://www.npmjs.com/package/concurrently) as a dev dep in the project and run with `concurrently` for all users.

If there are no significant issues other than running multiple commands concurrently for PowerShell users, I prefer the first option. If not, might consider the 2nd option.
Any thoughts on this?
