### ISSUE TITLE
How to store images of. md files?

### ISSUE THREAD

**Issue by ms06s** [satnaing/astro-paper#117]
I create an img folder under the content folder, which can be previewed in real time using an absolute path, but cannot be displayed when deployed to Netlify

**Comment by Jordain** [comment]
Make sure that your images are in the public folder

**Comment by satnaing** [comment]
There are two options to add images inside markdown files.

1) put the image inside the `public` folder. This will be served as it is, which means it will not be optimized by Astro.

      file: `about.md`
      
      ```md
      <!-- Assume example.jpg is inside /public/assets/example.jpg -->
      ![This is image alt text](@assets/images/example.jpg)
      ```

2) put the image inside `src/assets` folder. Then this image will be automatically optimized by Astro.

      file: `src/content/blog/adding-new-post.md`
      
      ```md
      <!-- Assume example.jpg is inside /src/assets/images/example.jpg -->
      ![This is image alt text](@assets/images/example.jpg)
      ```

I recommend the second option for most cases. But for some reason, the 2nd option is not working as expected inside `about.md` file. If so, you can use the first option. 

Hope this helps.

**Comment by MrGKanev** [comment]
@satnaing this and similar answers can be added as blog posts on the demo website? - this way people can use/customize the project more easier

**Comment by satnaing** [comment]
@MrGKanev 
Yep. Sure!
I'll add a blog post for these kinds of cases.
