### ISSUE TITLE
suggestion: add a "new page" command

### ISSUE THREAD

**Issue by rwillmer** [satnaing/astro-paper#13]
It would be really useful to have a command to generate a post with a standardised filename and boilerplate frontmatter.

For example,
astropaper new post <slug>

which would create a file called contents/YYYY-MM-DD-<slug> with all the frontmatter fields provided, date and slug fields automatically pre-filled.

**Comment by satnaing** [comment]
Thanks for this.

I'll try to implement command line `blog post generation` in the future releases.

**Comment by satnaing** [comment]
@rwillmer 
I've opened a PR for this feature. You can check it out and give feedback/suggestion if you want. You can also try it out in [feat/cli-generate-post](https://github.com/satnaing/astro-paper/tree/feat/cli-generate-post) branch.

**Comment by rwillmer** [comment]
PR works fine. I need to tweak it slightly; for my purposes I always use filenames YYYY-MM-DD-<slug> so I'd ask for the slug first and then default the filename to that format. But that might well not suit everyone, so I can just tweak that locally if you prefer your format.
Thanks for doing this so fast.

**Comment by satnaing** [comment]
Helo @rwillmer 

Sorry for my late reply. What I'm thinking right now is that in the future I might make a NodeJS CLI for AstroPaper to generate posts, tags and other stuff. 

So, at the moment, I'll leave my PR #14 without merging to the main branch. For those who want to generate blog posts via command line like you, they can clone [feat/cli-generate-post branch](https://github.com/satnaing/astro-paper/tree/feat/cli-generate-post).  I'll keep that branch in sync with my main branch so it will be update to date and has CLI post generation feature.

For now, I'll close this one. If you still have some issues, you can reopen this anytime. Thanks.
