### ISSUE TITLE
Create config constant for the lang attribute

### ISSUE THREAD

**Issue by fchrapek** [satnaing/astro-paper#133]
If you're using `LOCALE = ["en-EN"]` it might be worth adding the `LANG` constant and adjusting the `Layout.astro` so all the minimum language settings are in one place.

What do you think? I can handle the PR for it.

**Comment by satnaing** [comment]
🤔
I'm a bit confused about this. `LANG` from `src/config.ts` is currently only used inside `src/components/Datetime.tsx`.
Could you please provide a bit more detail on how you'd implement this?

**Comment by fchrapek** [comment]
Right, I wasn't very clear.

What I meant is that if you want to change the default, let's call them *language settings*, apart from the `LOCALE` variable, you also have to manually change the global `lang` attribute in the `Layout.astro` (currently it's set to `en`).

It's a minor thing, but it might improve the overall UX experience :)

**Comment by satnaing** [comment]
Good idea.
I'm thinking of something like LOCALE object. This is because html lang code and [BCP 47 Language](https://en.wikipedia.org/wiki/IETF_language_tag) can be different I guess.

```ts
export const LOCALE = {
  lang: "en", // html lang code. Set this empty and default will be "en"
  langTag: ["en-EN"], // BCP 47 Language Tags. Set this empty [] to use the environment default
} as const;
```

What do you think? You can PR if you want; and maybe I'll co-author.
