### ISSUE TITLE
Add Last Modified time to articles for SEO

### ISSUE THREAD

**Issue by saliksik** [satnaing/astro-paper#134]
Hi team,

I'm requesting that we add a Last Modified time feature to articles for search engine optimization (SEO).

This feature would display the date and time that an article was last updated on the page. This is important for SEO because it shows Google and other search engines that your content is fresh and up-to-date.

Here are some of the benefits of adding a Last Modified time feature to articles:

* **Improved SEO:** Search engines tend to rank fresh content higher than outdated content. Adding a Last Modified time feature to articles shows search engines that your content is up-to-date, which can help you improve your SEO rankings.
* **Increased user engagement:** Users are more likely to read and engage with articles that they know are up-to-date. Adding a Last Modified time feature to articles can help users see when an article was last updated, which can encourage them to read it.
* **Improved trust and credibility:** When users see that an article is up-to-date, they are more likely to trust the information in it. This can help you improve your credibility and authority as a thought leader in your industry.

I recommend that we add the Last Modified time feature to the article header, below the article title. This will make it easy for users and search engines to see when the article was last updated.

Thanks for your consideration!

**Comment by saliksik** [comment]
Additionally, we should add the following open graph meta tags (example) to articles:

```html
<meta property="article:published_time" content="2023-03-21T16:42:47+00:00" />
<meta property="article:modified_time" content="2023-03-21T16:42:54+00:00" />
```

These meta tags will be used by social media platforms to display the date and time that the article was published and modified when it is shared.

Thanks for your consideration!

**Comment by satnaing** [comment]
Thank you for pointing this out and explaining it in detail. 
This feature will be added in the next feature release, AstroPaper v3.1.0. 🤍

**Comment by satnaing** [comment]
Hello @saliksik 
I just made a PR #195  for this feature. 

You can give suggestions and feedback.

[Preview url](https://feat-article-modified-dateti.astro-paper.pages.dev/).
