### ISSUE TITLE
RSS Error [I got error when I click on RSS icon]

### ISSUE THREAD

**Issue by fountainpen** [satnaing/astro-paper#137]
[RSS] Invalid or missing options:
Invalid input (items)

**Comment by diomed** [comment]
![2023-09-29 08 21 37 localhost c297302cbcbe](https://github.com/satnaing/astro-paper/assets/72777/ede2127d-7e70-4232-843f-439c430c3781)

**Comment by satnaing** [comment]
Hello @fountainpen 
I don't see any problem with the RSS feature.
Can you provide more information so that I can reproduce the issue if it exists in AstroPaper.
