### ISSUE TITLE
<a> tag does not wrap the text on mobile screen size. 

### ISSUE THREAD

**Issue by gyunseo** [satnaing/astro-paper#139]
![gyunseo xyz_posts_analyze-cause-of-bsod_(iPhone SE) (1)](https://github.com/satnaing/astro-paper/assets/48322716/712e97aa-60c6-4606-ae41-c58d9c20a106)

I usually write my blog post using markdown link syntax `<url>`.
when my blog gets built, `<url>` syntax is converted to `<a></a>` tag on HTML document.
However, <a> tag does not wrap the text on mobile screen size.
I'm not familiar with tailwind CSS, so I cannot resolve this issue.
I think Someone or @satnaing can resolve this issue, and create a pull request.

Thank you
Best Regards
@gyunseo

**Comment by tanishqmanuja** [comment]
Thanks for reporting the issue. Can you confirm if the PR fixes the issue for you ?

**Comment by gyunseo** [comment]
> Thanks for reporting the issue. Can you confirm if the PR fixes the issue for you ?

@tanishqmanuja #140 fixed the issue. Thanks! :)
