### ISSUE TITLE
Feature request: Unlisted posts

### ISSUE THREAD

**Issue by ToddKerpelman** [satnaing/astro-paper#141]
There's been times when I've wanted to have a post published, but unlisted (so I can send to other folks to review before officially publishing it, but it doesn't show up in my home page anywhere). Unless I'm mistaken, it seems like adding `draft: true` stops the post from being published entirely. Would it make sense to either change the behavior of `draft:true` or maybe add new `draft: unlisted` value that allow for this?

**Comment by tanishqmanuja** [comment]
Is this feature about hiding the post only from home screen or other areas as well like - all posts section, and only make unlisted post available via URL and not the user interface?

**Comment by ToddKerpelman** [comment]
Yeah, I think it'd be best to hide it everywhere, and only make it available via the URL. 

I'm not super familiar with the code base, but it seems like you could do this by altering the logic in the [slug].astro file -- by being more lenient there, these pages could exist but not show up anywhere.

**Comment by satnaing** [comment]
Hello @ToddKerpelman , sorry for late response.

Hiding a blog post and enabling it to be able to access via url is not ideal for most use cases.
Generally, most users would only want to have two states_ draft or not.
For this reason, I'm not going to add that feature for now.

However, you can achieve that feature by following steps.

1) update `draft` schema property inside `config.ts`

```ts
// file: src/content/config.ts
const blog = defineCollection({
  type: "content",
  schema: ({ image }) =>
    z.object({
      // other codes
      draft: z.literal("unlisted").or(z.boolean()).optional(), // make sure to add "unlisted" string literal
      tags: z.array(z.string()).default(["others"]),
      // other codes
    }),
});

export const collections = { blog };
```

2) update `getStaticPaths` inside `[slug]/index.astro`

```ts
export async function getStaticPaths() {
  const posts = await getCollection(
    "blog",
    ({ data }) => data.draft === "unlisted" || !data.draft // 👈🏻 update post conditional check
  );
  // other codes
```

3) Now, you can add `draft: "unlisted"` inside a blog post; and it will be hidden and will only be accessible via URL

eg: src/content/blog/example.md
```astro
---
author: Your Name
pubDatetime: 2024-09-25T10:25:54.547Z
title: Your title
postSlug: your-title
draft: "unlisted"
// other
```

Hope this helps!
