### ISSUE TITLE
OG Image is not being generated properly on CloudFlare

### ISSUE THREAD

**Issue by mattppal** [satnaing/astro-paper#142]
I'm not quite sure what's going on, but when I check the OG Image for my site, I see the default

![image](https://github.com/satnaing/astro-paper/assets/59450879/04ea0a4a-3f12-4983-b436-235367075f1d)

Oddly, I can confirm that on `npm run build`, the correct image is generated at `/og.png` 

![og](https://github.com/satnaing/astro-paper/assets/59450879/2ccd87ba-3145-40c2-ba4c-8670f48336f7)

Any ideas what is happening?

Here's my `config.ts`, all vars should be defined properly

```
import type { Site, SocialObjects } from "./types";

export const SITE: Site = {
  website: "https://mattpalmer.io",
  calendar: "https://calendar.app.google/mVAr85FzJQqzpVce9",
  linkedin: "https://linkedin.com/in/matt-palmer",
  author: "Matt Palmer",
  desc: "Matt's musings— all things data, writing, & fun.",
  title: "MattPalmer",
  jobTitle: "Developer Success Engineer",
  email: "hello@mattpalmer.io",
  team: "Data",
  company: "Mage",
  location: "San Jose, CA",
  googleAnalyticsId: "",
  lightAndDarkMode: true,
  postPerPage: 8,
};
```

**Comment by tanishqmanuja** [comment]
You will need to update the astro config as well :)

**Comment by tanishqmanuja** [comment]
@satnaing, Currently we have to set both website in config and site in astro config. Both are required as astro.site is only available in .astro files. Can we somehow make a single source of truth, what do you think?

**Comment by mattppal** [comment]
@tanishqmanuja Maybe I'm a bit confused, but the `site.tsx` appears to be imported from `@config`...

```
import { SITE } from "@config";

export default () => {
  return (
    <div
      style={{
```

**Comment by tanishqmanuja** [comment]
@mattppal, what actually links the image url to html, are the og meta tags, which are present in the layouts/Layout.astro

**Comment by mattppal** [comment]
Ah, I see now— yeah it's kind of sneaky that without changing `site` in `astro.config.mjs`, the social images will pull defaults 😬 

Thank you very much for your explaination

**Comment by satnaing** [comment]
> @satnaing, Currently we have to set both website in config and site in astro config. Both are required as astro.site is only available in .astro files. Can we somehow make a single source of truth, what do you think?
> 
> One Option is:
> 
> ```js
> import { SITE } from "./src/config";
> 
> // https://astro.build/config
> export default defineConfig({
>   site: SITE.website,
>   // more stuff
> ```

@tanishqmanuja 
Yes, I was aware of it and tried merging the two options together. But when I did the approach you mentioned, I faced some bugs. Not sure if that bug still exists now. If not, you can make a PR for that.
