### ISSUE TITLE
w3 validator errors

### ISSUE THREAD

**Issue by kadvoscp** [satnaing/astro-paper#149]
When I pasted the URL of your astro paper theme, https://astro-paper.pages.dev/, into https://validator.w3.org/ (W3C official validator), I found some errors there that you should also take a look at. There are errors in each page you need to check each page separately. These errors significantly affect the SEO of a particular website. Additionally, I suggest that whenever you make any changes, you should just check it once in the W3C validator before actually committing them.

**Comment by tanishqmanuja** [comment]
You sure this site is up do date with the bleeding edge web tech?
![image](https://github.com/satnaing/astro-paper/assets/40914272/9feecb4c-974b-4098-9f64-04b9700e94e7)

Refer:
https://developer.mozilla.org/en-US/docs/Web/CSS/view-transition-name

PS: Nothing to worry Astro provides fallback for the browsers that don't support view transitions API :)

**Comment by satnaing** [comment]
@kadvoscp 
Thanks for your suggestion. 
A lot of browsers still don't support CSS view-transition api yet; and that's why that log appears. 
As @tanishqmanuja said, that should not be a big problem.
So, I'll close this issue for now.
