### ISSUE TITLE
back to top

### ISSUE THREAD

**Issue by diomed** [satnaing/astro-paper#156]
could you integrate back to top button

**Comment by SP58** [comment]
@satnaing

**Comment by Because789** [comment]
I was annoyed how clumsy the solution in my pull request yesterday was. So I added in my AstroPaper playground a new component: [NavButton.astro](https://github.com/Because789/astro-blog/blob/main/src/components/NavButton.astro). The new component is used here: [PostDetails.astro](https://github.com/Because789/astro-blog/blob/main/src/layouts/PostDetails.astro).

I'm very new to Astro, so I guess it still could be solved more elegantly. But hey, it's a start.
