### ISSUE TITLE
Social Links section set to OFF if no links

### ISSUE THREAD

**Issue by strauhmanis** [satnaing/astro-paper#16]
Hey,

The following enhancement should be made — the _Social Links_ section should not be displayed when no links are activated in the config.

Thanks!

![Screenshot](https://user-images.githubusercontent.com/17160191/209797745-d07b277c-f982-4658-afa5-9eefba0d3975.png)

**Comment by satnaing** [comment]
Oh, I didn't notice that.
Thanks for pointing this out @strauhmanis
