### ISSUE TITLE
Add limit in featured post 

### ISSUE THREAD

**Issue by rakrisi** [satnaing/astro-paper#165]
## Add limit in featured post 
when I add many featured posts then it shows all featured posts but generally, we want the top 5 or top 10 feature post to show depending upon the latest feature post

const featuredPosts = sortedPosts.filter(({ data }) => data.featured).slice(0, 5); in index.astro page
like this way

@satnaing what's your thought on it.

**Comment by fchrapek** [comment]
@rakrisi one could probably argue that if you have more than 5 featured post then they are not really featured anymore

**Comment by rakrisi** [comment]
yes @fchrapek ,it may be the case.

today I deployed few articles and saw many feature posts on my main index page. that's why I thought it should have a limit and be configurable from ENV.

```js
const FeaturedPostLimit = import.meta.env.FeaturedPostLimit;

let featuredPosts = sortedPosts.filter(({data}) => data.featured);
if (featuredPosts.length > 0) {
  featuredPosts = featuredPosts.slice(0, FeaturedPostLimit);
}
```

i done it this way. it does not impact others. who don't have env configured.

**Comment by fchrapek** [comment]
@rakrisi sure, if it works for you than great :) 

What I meant is that personally I'm not setting more than 3 posts as featured, because the 'featured' label IMO should be used rather carefully, since you want to highlight only few selected posts.

**Comment by rakrisi** [comment]
@fchrapek true.
