### ISSUE TITLE
feature: verify mastodon acount with link in header

### ISSUE THREAD

**Issue by maheshrijal** [satnaing/astro-paper#167]
Thank you for your efforts. Please consider adding [mastodon verification](https://joinmastodon.org/verification) support for the theme.

**Comment by hellquist** [comment]
You can easily add this yourself if you add the `<link rel="me" href="https://myMastodonInstanceURL/@yourusername" />` in the `src/layouts/Layout.astro` file. Just tried it myself, worked perfectly. I put my links (I have several) under  the existing `<meta name="generator" content={Astro.generator} />` right in the `<head>` section.

**Comment by satnaing** [comment]
Close this for now.
I hope users can do this themselves if they want.
