### ISSUE TITLE
Create a default docker compose configuration

### ISSUE THREAD

**Issue by eerison** [satnaing/astro-paper#172]
I guess we could add a default docker-compose config file to make astro paper work without install dependencies locally.

**Comment by satnaing** [comment]
I can't run the app without running `docker compose run app npm install`. Then `node_modules` will appear in my local machine. 
Can you tell me some steps to run docker-compose file?

Docker is not my area of expertise, and thus you can tell me if I'm wrong.
Here are my steps
1) install dependencies with `docker compose run app npm i`
2) run docker-compose with `docker compose up -d`
