### ISSUE TITLE
Upgrade to astro 4.0

### ISSUE THREAD

**Issue by alec-c4** [satnaing/astro-paper#187]
As you maybe know - Astro 4 have [arrived](https://astro.build/blog/astro-4/). Are there any plans to upgrade AstroPaper to a new version?

**Comment by satnaing** [comment]
Of course, I'll upgrade to Astro v4.
However, at the moment, I've been trying to solve some issues for now.
After that, I'll upgrade.

Busy these days 😅
Thanks for reminding me.

**Comment by diomed** [comment]
how could I send you my own theme scheme suggestion?
maybe here?

would you update with it?

**Comment by vasfvitor** [comment]
With just `pnpm dlx @astrojs/upgrade` it upgrades and builds normally. I went quickly through https://docs.astro.build/en/guides/upgrade-to/v4/ but any changes that might needed was already addressed

btw, is shamefully-hoist=true still needed? I remember this being a thing but now I guess it not necessary, 
https://discord.com/channels/830184174198718474/845430950191038464/1024702697938632734.

**Comment by jeanlucaslima** [comment]
@satnaing if you need any help just create some issues and we can contribute.

**Comment by diomed** [comment]
> @satnaing if you need any help just create some issues and we can contribute.
you can even contribute without issues. just by sending PR's. he'll accept if ok.

**Comment by jeanlucaslima** [comment]
@diomed are you sure? Not all repos are like this.

**Comment by jeanlucaslima** [comment]
Just did on #200

**Comment by satnaing** [comment]
> how could I send you my own theme scheme suggestion? maybe here?
> 
> would you update with it?

Yep. @diomed 
I'll make a PR for v4 upgrade and you can suggest under that.

**Comment by satnaing** [comment]
> @satnaing if you need any help just create some issues and we can contribute.

Appreciate it.
You all can give suggestions and feedback (maybe contribute) on my v4 PR later.

**Comment by satnaing** [comment]
> I built my blog when this theme was using version 2 of Astro. I've had huge problems trying to upgrade. Do you have any advice? This is the issue I created in the [Astro Discord channel](https://discord.com/channels/830184174198718474/1184845294219837440)

@o-t-w sorry to hear your inconvenience
Maybe you can try by following [this article](https://astro-paper.pages.dev/posts/how-to-update-dependencies/)?
As a maintainer, it's hard to cover a lot of use cases and different customizations. 

On one hand, there're new breaking changes and features by Astro itself, plus some additional features by AstroPaper. On the other hand, there are a lot of users (like you) who want to upgrade smoothly. 
One of the easiest way to upgrade, in my opinion, is saving your customizations and contents, get the latest AstroPaper, then apply your previous customizations accordingly.

There might be some better ways to do this. So let me know if you guys have better approach. Maybe changes I have to make for better customizations.

**Comment by jeanlucaslima** [comment]
> > @satnaing if you need any help just create some issues and we can contribute.
> > @jeanlucaslima   you can even contribute without issues. just by sending PR's. he'll accept if ok.

Like I said... Not all repos like outside PRs :^) no hard feelings, it's just common
