### ISSUE TITLE
Searching for article behaviour

### ISSUE THREAD

**Issue by Sahillather002** [satnaing/astro-paper#203]
Didn't get any result for single character.
![image](https://github.com/satnaing/astro-paper/assets/72077931/3a5afd88-96ef-4877-8ce6-a4909deb5a2c)

When searched for some character 'abcde' it shows nothing:
![image](https://github.com/satnaing/astro-paper/assets/72077931/a8b4fc15-66b3-40a6-9c56-1a065cf23af4)

But when i did with 'abcdef' shows this:
![image](https://github.com/satnaing/astro-paper/assets/72077931/f0c4b5f6-4ccb-4286-aafb-f3de3cc901db)

I think behaviour is not perfectly alligned.

**Comment by kishoreandra** [comment]
Hey @Sahillather002  ... I guess that was intentional, I have gone through the code https://github.com/satnaing/astro-paper/blob/bb60a9b3db733a4561df2464ae3d6e3944dd25ef/src/components/Search.tsx#L59 ... The search triggers after entering 2 or more char's and results appear if that exists ..

**Comment by Sahillather002** [comment]
cool then
