### ISSUE TITLE
Adding reading time post does not include the Tag files 

### ISSUE THREAD

**Issue by SSmale** [satnaing/astro-paper#205]
https://github.com/satnaing/astro-paper/blob/main/src/content/blog/how-to-add-an-estimated-reading-time.md

to get this to work on mine I needed to add await to the `getPostsByTag` method in the index.astro. 

I might also need to do the same in the [page].astro too

**Comment by satnaing** [comment]
Yep
I think I've also mentioned that in [this blog post](https://astro-paper.pages.dev/posts/how-to-add-estimated-reading-time/#access-reading-time-outside-of-postdetails-optional).

**Comment by SSmale** [comment]
Hi @satnaing, I could not see that in the post, that's why I made the issue
