### ISSUE TITLE
Forestry will be discontinued

### ISSUE THREAD

**Issue by beeburrt** [satnaing/astro-paper#21]
Announced here:

https://forestry.io/blog/forestry.io-end-of-life/

Don't know how this will effect you.

**Comment by satnaing** [comment]
Didn't notice that. Thanks for info. ✌🏻

**Comment by beeburrt** [comment]
So would you recommend using Tina?

**Comment by satnaing** [comment]
I've no idea at the moment since I haven't tried that yet. I'll update my blog post about Forestry after testing some other headless CMS including Tina.

**Comment by eerison** [comment]
I am testing Tina.

But I am getting this error when I try to open /admin/index.html


> Failed loading TinaCMS assets
> Your TinaCMS configuration may be misconfigured, and we could not load the assets for this page.
> Please visit [this doc](https://tina.io/docs/tina-cloud/faq/#how-do-i-resolve-failed-loading-tinacms-assets-error) for help.

any idea?

**Comment by eerison** [comment]
Hey @satnaing 

in case you have sometime, could you help me figure out why I can't make contextual edit works in tina cms?

here is a example using astro: https://github.com/Klrfl/simple-blog-with-tina/blob/main/src/pages/posts/%5B...slug%5D.astro

But it looks a bit different of astro-paper structure, and I can not make this work :(

and other question .. why are you defining this : https://github.com/satnaing/astro-paper/blob/main/src/pages/posts/%5Bslug%5D/index.astro#L6-L8, as I can see blog keep working without it
