### ISSUE TITLE
Can more View Transitions be used

### ISSUE THREAD

**Issue by xiyuvi** [satnaing/astro-paper#227]
https://developer.chrome.com/docs/web-platform/view-transitions
May I ask if you can refer to the example to add more beautiful View Transitions to the paper?

For example, overall left and right movement animation or other, thank you to the developer, God bless you

**Comment by satnaing** [comment]
Thanks @xiyuvi 
I'll put more effort into adding new features and better transitions in future releases.
However, I'll close this issue for now.
