### ISSUE TITLE
Integrate Giscus comments

### ISSUE THREAD

**Issue by FjellOverflow** [satnaing/astro-paper#250]
With [Giscus](https://giscus.app/) one can neatly integrate comments into a static blog. I wrote a guide on how to do that for AstroPaper: https://fjelloverflow.dev/posts/how-to-add-giscus/

I think this is a nice opt-in feature for AstroPaper to have. Should I
- Open a PR to integrate opt-in Giscus comments?
- Open a PR to add this tutorial to the AstroPaper documentation?
- Put the tutorial/link to tutorial into the FAQ section?

I like contributing to AstroPaper, let me know if you are interested in this feature.

**Comment by satnaing** [comment]
Love it.
Can you make a PR for a tutorial blog post? @FjellOverflow
