### ISSUE TITLE
Generating page images does not support Chinese titles？

### ISSUE THREAD

**Issue by mingxia** [satnaing/astro-paper#256]
Today I tried to publish an article with a Chinese title. When I forwarded it to Twitter, I found that the Chinese characters in the generated pictures had changed to "口口口口". How can I solve this problem to support these words?

**Comment by llccing** [comment]
Hi Bro, did you soved this? cloud you share me some message about this?

**Comment by llccing** [comment]
i found that, although i throw errors, but the content can still generated. but it still a issue, right?
