### ISSUE TITLE
how do I change the Mingalaba in the front page? I cannot seem to find a way to update the whole section, neither find the index html either. Please help me out.

### ISSUE THREAD

**Issue by retrogtx** [satnaing/astro-paper#257]
I want to update it with my own custom bio.

https://amritwt.vercel.app/

**Comment by everonegraham** [comment]
You can find it here: https://github.com/satnaing/astro-paper/blob/main/src/pages/index.astro#L26

**Comment by retrogtx** [comment]
> You can find it here: https://github.com/satnaing/astro-paper/blob/main/src/pages/index.astro#L26

thanks!

**Comment by satnaing** [comment]
I believe this issue has already been resolved.
Thus, closing this for now.
If you have any problems, you can open a new issue or start a discussion.
I appreciate your understanding.
