### ISSUE TITLE
Incorrect use of aria-labels

### ISSUE THREAD

**Issue by rogierv88** [satnaing/astro-paper#263]
Some elements have `aria-labels` that can not have these labels. Aria labels should only be applied on interactive elements or HTML landmarks.
As far as I could find this applies to the 404 `h1` element and the disabled version of the LinkButton element.

**Comment by benjaminrae** [comment]
As far as I can see this use of `aria-label` is valid according to https://w3c.github.io/aria/#aria-label

However as it says `title` may be preferred but would create a tooltip, or even `aria-labelled-by`.

**Comment by rogierv88** [comment]
As stated on [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labe](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labe)l, the `aria-label` should only be used on interactive elements or HTML landmarks. Which is not the case for an `h1` or `span` element.

**Comment by satnaing** [comment]
Thanks for pointing this out! 
This issue will be fixed in #346
