### ISSUE TITLE
Build failed on Vercel - Failed to create `_jampack` folder.

### ISSUE THREAD

**Issue by Pramuspl** [satnaing/astro-paper#277]
When I try to deploy it to Vercel in SSR hybrid mode, the `npm run build` fails due to `Failed to create ``_jampack`` folder.`.
Before installing the adapter it worked fine as a static page.

<img width="643" alt="image" src="https://github.com/satnaing/astro-paper/assets/8478114/92c4b4a7-1eb9-4ce5-9362-e05452d4a9b4">

**Comment by jjaimealeman** [comment]
The package you are referring to is `divriots/jampack`

After reading through their site and docs, it only mentions use for `SSG`, sadly not a single mention of `SSR` :( 

https://divriots.com/blog/introducing-jampack/
