### ISSUE TITLE
How change «Table of contents» lettering?

### ISSUE THREAD

**Issue by AliIslamov** [satnaing/astro-paper#278]
I whant change «Table of contents» and «Open Table of contents» letterings, but I can't find where can I do it?

**Comment by benjaminrae** [comment]
By lettering do you mean the font? Or do you mean the text content?

**Comment by AliIslamov** [comment]
> By lettering do you mean the font? Or do you mean the text content?

I mean the text content. And I already have found the solution.

I changed `astro.config.ts` from

```typescript
...
remarkPlugins: [
      [remarkToc, { heading: 'NewTableContentLabel' }]
    ],
```

To

```typescript
...
remarkPlugins: [
      remarkToc,
      [
        remarkCollapse,
        {
          test: "Table of contents",
        },
      ],
    ],
```

So I made the content list permanently visible and changed the list title to a custom one.

**Comment by jeanlucaslima** [comment]
How to change the table-of-contents id?

**Comment by gitboyzcf** [comment]
remarkPlugins: [[remarkToc, { heading: '目录' }], [remarkCollapse, { test: "目录", summary: '点击展开' }]]
