### ISSUE TITLE
Right alignment of text in *.md fille

### ISSUE THREAD

**Issue by AliIslamov** [satnaing/astro-paper#279]
I have several *.md posts in content folder. Each post contains several RTL block of texts.

How can I align several paragraphs of text inside a *.md file to the right side when displayed on a website?

**Comment by benjaminrae** [comment]
You might find that manually adding html makes this easier.

Something like:

```
<p align="right", dir="rtl", lang="...">
  ...
</p>
```

**Comment by AliIslamov** [comment]
> You might find that manually adding html makes this easier.
> 
> Something like:
> 
> ```
> <p align="right", dir="rtl", lang="...">
>   ...
> </p>
> ```

Yes, I came to the same conclusion.  It's disappointing that markdown doesn't have its own alignment tools.
