### ISSUE TITLE
Issue about `Content Collections` with `astro build` command

### ISSUE THREAD

**Issue by BenjaminDbb** [satnaing/astro-paper#283]
The static files generated using `astro dev` and `astro build & preview` are different. 
Using `astro build & preview` will cause some markdown files to not be displayed in `/posts/index.html`. 
For example, there are three group-meeting files in [blog folder](https://github.com/hnasgravity/hnasgravity.github.io/tree/main/src/content/blog) , but the website will only display [2 blogs](https://hnasgravity.github.io)

However, everything goes OK with `astro dev`.

**Comment by Plortinus** [comment]
Hello @BenjaminDbb .Same problem, how did you solve it ?
