### ISSUE TITLE
How do I add a `Notes` tab, similar to `Posts`

### ISSUE THREAD

**Issue by zcyc** [satnaing/astro-paper#284]
I need three categories on tab, including notes, posts, and talks.
How do I achieve this, can anyone give me a list of code changes?

**Comment by maheshrijal** [comment]
I've listed my notes [here](https://github.com/satnaing/astro-paper/discussions/311). You can let me know if it does not work for you. 

https://github.com/satnaing/astro-paper/discussions/311

**Comment by satnaing** [comment]
Updated!!!
You can check [this discussion](https://github.com/satnaing/astro-paper/discussions/342#discussioncomment-10222742) answered by @maheshrijal
