### ISSUE TITLE
Generate new post/article.

### ISSUE THREAD

**Issue by Yasir-Khan22** [satnaing/astro-paper#287]
Complete Beginner to SSG like astro. Wanted to know more about like How can we generate our own version of articles, posts in this type of portfolio.

**Comment by vivekdhami** [comment]
This provides a good introduction to Astro: https://docs.astro.build/en/tutorial/0-introduction/

**Comment by satnaing** [comment]
If you want to learn more about Astro and its feature, I recommend [Astro's Docs](https://docs.astro.build/en/getting-started/) and its [blog tutorial](https://docs.astro.build/en/tutorial/0-introduction/).
If you want to generate new posts, you can integrate sort of [git-based CMS](https://jamstack.org/headless-cms/).
Another option would be using VSCode and [code-snippet to create boilerplate codes](https://astro-paper.pages.dev/posts/astro-paper-v4/#add-code-snippets-for-content-creation-206).
Hope this comment helps you in some way.

Closing this issue for now.
If you have any problems, feel free to open a new issue or start a discussion.
Thanks for your understanding.
