### ISSUE TITLE
Following installation steps doesn't create Astro with template

### ISSUE THREAD

**Issue by danielrosehill** [satnaing/astro-paper#297]
Maybe I'm going crazy or missing something very basic. This worked for me yesterday but that involved cloning the repo.

I follow the installation step in the readme trying to install Astro with the theme:

`npm create astro@latest --template satnaing/astro-paper`

All looks to run fine and it seems to be pulling the template correctly:

![image](https://github.com/satnaing/astro-paper/assets/40233203/e932fbac-8d44-456e-8e25-06f542d04302)

But the system has created the default template!

![image](https://github.com/satnaing/astro-paper/assets/40233203/674c7f51-9b80-4cd0-948e-812073300536)

Visiting `localhost:4321` : 

![image](https://github.com/satnaing/astro-paper/assets/40233203/a820d959-30f2-474e-9eec-4ef2f838e88b)

Am I doing something wrong?

**Comment by 2wheeh** [comment]
try with `npm create astro@latest -- --template @satnaing/astro-paper`

**Comment by satnaing** [comment]
I believe this one is resolved already.
If you have any other issue, you can reopen this or open another issue.
Thanks!
