### ISSUE TITLE
You should get on this list...

### ISSUE THREAD

**Issue by beeburrt** [satnaing/astro-paper#30]
Awesome Astro

https://github.com/one-aalam/awesome-astro

You should open a pull request to include Astro Paper in that list.

**Comment by satnaing** [comment]
Hello @beeburrt,

Thanks for the suggestion to include AstroPaper in the Awesome Astro repository. However, at the time of writing this, I might/would not create a PR in [awesome-astro](https://github.com/one-aalam/awesome-astro) as AstroPaper's already been featured in the official Astro theme section. And, on my behalf, if someone wants to include or create a PR to include AstroPaper in awesome-astro (or any other repo/sites), that's also fine.

Again, thanks ✌🏻
