### ISSUE TITLE
Publishing to Netlify: latest post doesn't show up.

### ISSUE THREAD

**Issue by danielrosehill** [satnaing/astro-paper#300]
Trying to troubleshoot this issue.

Local environment, post is fine:

![image](https://github.com/satnaing/astro-paper/assets/40233203/eb1cebef-5c74-4179-9bcf-ce26272630c1)

But after deploying to Netlify the post doesn't show up anywhere:

![image](https://github.com/satnaing/astro-paper/assets/40233203/db15827e-a0dc-42c4-a056-ac9c7c4799e0)

**Comment by di-dc** [comment]
Just a guess based on pubDateTime in your screenshot vs the date/time when you posted this -- is the pubDateTime in the future?

If so: https://github.com/satnaing/astro-paper/pull/234

**Comment by danielrosehill** [comment]
Yup. Sorry @di-dc (and thanks)

**Comment by satnaing** [comment]
I hope this issue is already resolved. 
I'm closing it for now.
