### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by theapplegates** [satnaing/astro-paper#302]
I am getting "Invalid Date" where the post date should be.
I checked for console for errors and got litterly none. Any ideas?
![Invalid_Date](https://github.com/satnaing/astro-paper/assets/27178137/8c9fb8f3-7c5f-4dd0-84fc-1fd0cd507966)

**Comment by No1ceTea** [comment]
Did you change something in the code ?
It's a fresh fork ?

**Comment by theapplegates** [comment]
I must be sleep coding. I look at my commits and expected to only see syncing the the fork as I have not modified.
I see this commit, src/components/Datetime.tsx I don't even know how to show the change, 1 parent [c00a3aa](https://github.com/theapplegates/astro-paper/commit/c00a3aa5dc4706a4f833266a0b24bca1253ccce4)
commit 24bf875 , that might work. I'm going to delete my commit and copy the correct version of Datetime.tsx. Give me one min. I apologize for my confusion.

**Comment by theapplegates** [comment]
It's fine now. I swear I had no idea. Once again I'm sorry. Have a good day.
