### ISSUE TITLE
Any chance of guidance for basic CSS modifications?

### ISSUE THREAD

**Issue by danielrosehill** [satnaing/astro-paper#303]
Hey!

I'm working on editing the typography of my website built with Astro Paper.

I would like to edit some of the CSS classes like this to make the typeface used in the articles a bit bigger

![image](https://github.com/satnaing/astro-paper/assets/40233203/9b207732-1805-4205-8768-eadc333cc011)

And also change the font used for the article titles.

And finally increase the font size of the article previews on the homepage:

![image](https://github.com/satnaing/astro-paper/assets/40233203/30367bf3-b41d-456d-b155-8797d07fcf3e)

Is there any documentation available for where these classes might be found in the codebase?

TIA

**Comment by FjellOverflow** [comment]
This project uses [Tailwind CSS](https://tailwindcss.com/), a CSS framework, where the classes `mx-*, mt-*, max-w-*` originate from. You can configure it by modifying `tailwind.config.cjs`.
Typography specifically comes from [@tailwindcss/typography](https://github.com/tailwindlabs/tailwindcss-typography), also described [here](https://astro-paper.pages.dev/posts/tailwind-typography/).
Also just searching the project shows the `prose` class you mention is modified in `src/styles/base.css`.

**Comment by satnaing** [comment]
I hope @FjellOverflow's reply answers your question. @danielrosehill 
If you still have any style-specific issues, please open a new issue. 
I'll close this one for now.

**Comment by Ra2-IFV** [comment]
> I hope [@FjellOverflow](https://github.com/FjellOverflow)'s reply answers your question. [@danielrosehill](https://github.com/danielrosehill) If you still have any style-specific issues, please open a new issue. I'll close this one for now.

In latest commit this file does not work. Do you renamed this file to `global.css` ?
