### ISSUE TITLE
Categories Need to add categories feature in menu 

### ISSUE THREAD

**Issue by fazi-gondal** [satnaing/astro-paper#306]
Sir please add categories feature in astro-paper

**Comment by No1ceTea** [comment]
You can use "tag" to categorize article

**Comment by fazi-gondal** [comment]
> You can use "tag" to categorize article

Thank you sir

**Comment by fazi-gondal** [comment]
> You can use "tag" to categorize article

Bro can you make a separate categories page in astro paper theme for categories feature

**Comment by satnaing** [comment]
Thanks for your suggestion. 
However, at the time of writing this, creating a separate categories page isn't within the current scope of the theme. 
Thank you for understanding.
