### ISSUE TITLE
Blog header should support blog deployed at <root.url/base> in addition to <root.url>

### ISSUE THREAD

**Issue by davidandreoletti** [satnaing/astro-paper#312]
Blog header should not hardcode website root to [`/`](https://github.com/satnaing/astro-paper/blob/c00a3aa5dc4706a4f833266a0b24bca1253ccce4/src/components/Header.astro#L17) but `/<base>` to support website deployed at `/<base>`.

When `<base>` is empty, the original behaviour is preserved.

**Comment by No1ceTea** [comment]
Do a PR

**Comment by davidandreoletti** [comment]
I initially considered it. 

However, I decided to develop my own blog from scratch. 

Easier to satisfait all my other requirements.

**Comment by No1ceTea** [comment]
Okay, Good luck ! 
I am intersted, when you finish it, feel free to share it to me !

**Comment by davidandreoletti** [comment]
Thank you.

Unfortunately, this will be a private repo.

**Comment by satnaing** [comment]
Hello @davidandreoletti 
You mean something like this? 

```ts
import { SITE } from "@config";

---
<a href={SITE.website ?? "/"}>Home</a>
```

**Comment by satnaing** [comment]
I think you meant something like this. (Correct me if I'm wrong)

```astro
<a
  href=`${import.meta.env.BASE_URL}/posts/`
  class={activeNav === "posts" ? "active" : ""}
>
  Posts
</a>
```

The thing is that it is not suitable for every scenario. 
It works if `base` is specified properly other than `/`.
It won't work well if `base` is not specified or set to `/`.

The [docs](https://docs.astro.build/en/guides/routing/#navigating-between-pages) itself is suggesting like this:

```astro
<p>Read more <a href="/about/">about</a> Astro!</p>

<!-- With `base: "/docs"` configured -->
<p>Learn more in our <a href="/docs/reference/">reference</a> section!</p>
```

Please, do let me know if you have any solution I missed. @davidandreoletti 
Thanks.

**Comment by satnaing** [comment]
Closing this issue for now.
Feel free to reopen it if you’d like to continue the discussion.
Thanks for your understanding.
