### ISSUE TITLE
Google Tag

### ISSUE THREAD

**Issue by AmauryVanEspen** [satnaing/astro-paper#348]
Hi,

could you be a bit more explicit with
`# in your environment variable file (.env)
PUBLIC_GOOGLE_SITE_VERIFICATION=your-google-site-verification-value`

where should be store the .env file at the root folder structure ? it seems it doesn't exist when cloning repository and I did'nt found any reference in the code repo's and files available

thanks

Amaury

**Comment by satnaing** [comment]
Maybe [this](https://github.com/satnaing/astro-paper/discussions/334#discussioncomment-10139247) helps?
The `.env` file should be created at the root level. [Astro Docs](https://docs.astro.build/en/guides/environment-variables/)
I'll rewrite it a bit more explicitly in the future.

**Comment by AmauryVanEspen** [comment]
Hi @satnaing 
could you provide some sample of what the .env file should contains and where should it be there ? 
just build a .env from scratch at the root folder and insert a ligne for Google Site Verification ?
I do not see the enhancement of the readme related to Google Site Verification and where the google tag appears afterwards
Thanks
