### ISSUE TITLE
posts.slice is not a function

### ISSUE THREAD

**Issue by manthanank** [satnaing/astro-paper#350]
- In `utils/getPagination.ts:26:32` getting error while adding estimated reading time in AstroPaper

**Comment by manthanank** [comment]
In `src/utils/getPostsByTag.ts` updated a shown below

```
import type { CollectionEntry } from "astro:content";
import getSortedPosts from "./getSortedPosts";
import { slugifyAll } from "./slugify";

const getPostsByTag = async(posts: CollectionEntry<"blog">[], tag: string) =>
  await getSortedPosts(
    posts.filter(post => slugifyAll(post.data.tags).includes(tag))
  );

export default getPostsByTag;

```

**Comment by manthanank** [comment]
In `src/utils/getPagination.ts` getting an error at line 26 from the code below:

```
import { SITE } from "@config";
import getPageNumbers from "./getPageNumbers";

interface GetPaginationProps<T> {
  posts: T;
  page: string | number;
  isIndex?: boolean;
}

const getPagination = <T>({
  posts,
  page,
  isIndex = false,
}: GetPaginationProps<T[]>) => {
  const totalPagesArray = getPageNumbers(posts.length);
  const totalPages = totalPagesArray.length;

  const currentPage = isIndex
    ? 1
    : page && !isNaN(Number(page)) && totalPagesArray.includes(Number(page))
      ? Number(page)
      : 0;

  const lastPost = isIndex ? SITE.postPerPage : currentPage * SITE.postPerPage;
  const startPost = isIndex ? 0 : lastPost - SITE.postPerPage;
  const paginatedPosts = posts.slice(startPost, lastPost);

  return {
    totalPages,
    currentPage,
    paginatedPosts,
  };
};

export default getPagination;
```

**Comment by manthanank** [comment]
![Screenshot 2024-08-11 133021](https://github.com/user-attachments/assets/d9c370b2-75c6-488b-8ac7-fde8bed62f9e)
![Screenshot 2024-08-11 133124](https://github.com/user-attachments/assets/9ae17445-a63e-46f9-aad8-8a6a37ffea19)

**Comment by satnaing** [comment]
Yes.
You have to add the keyword `await` in all `getSortedPosts` functions.

```
const sortedPosts = await getSortedPosts(posts); // ✅
```

**Comment by satnaing** [comment]
I have updated the blog post in #354 and it automatically closes this issue.
You can reopen this if you still have the problem. 
Thanks

**Comment by manthanank** [comment]
It is not fixed, on hovering tags getting an error!

**Comment by satnaing** [comment]
Still the same error as the screenshot above?
Did you add `await` in every `getSortedPosts` function?

**Comment by manthanank** [comment]
> In `src/utils/getPostsByTag.ts` updated a shown below
> 
> ```
> import type { CollectionEntry } from "astro:content";
> import getSortedPosts from "./getSortedPosts";
> import { slugifyAll } from "./slugify";
> 
> const getPostsByTag = async(posts: CollectionEntry<"blog">[], tag: string) =>
>   await getSortedPosts(
>     posts.filter(post => slugifyAll(post.data.tags).includes(tag))
>   );
> 
> export default getPostsByTag;
> 
> ```

Except here everywhere added

**Comment by satnaing** [comment]
I got the exact same error in the screenshot above if I don't `await` the `getSortedPosts` function.

Make sure you have updated the following files.
- [ ] src/pages/index.astro
- [ ] src/pages/rss.xml.ts
- [ ] src/pages/search.astro
- [ ] src/pages/posts
- [ ] src/pages/posts/[slug]/index.astro
- [ ] src/utils/getPostsByTag.ts

You'll also need to add `await` keyword in front of `getPostsByTag` function.

- [ ] src/pages/tags/[tag]/[page].astro
- [ ] src/pages/tags/[tag]/index.astro

**Comment by manthanank** [comment]
> I got the exact same error in the screenshot above if I don't `await` the `getSortedPosts` function.
> 
> Make sure you have updated the following files.
> 
> * [ ]  src/pages/index.astro
> * [ ]  src/pages/rss.xml.ts
> * [ ]  src/pages/search.astro
> * [ ]  src/pages/posts
> * [ ]  src/pages/posts/[slug]/index.astro
> * [ ]  src/utils/getPostsByTag.ts
> 
> You'll also need to add `await` keyword in front of `getPostsByTag` function.
> 
> * [ ]  src/pages/tags/[tag]/[page].astro
> * [ ]  src/pages/tags/[tag]/index.astro

It working now

**Comment by manthanank** [comment]
![image](https://github.com/user-attachments/assets/04dc9539-1e9b-453d-8590-635d427fc0fc)

It worked in build fails

**Comment by satnaing** [comment]
Can you share me the file `src/pages/tags/[tag]/[page].astro` here ?

**Comment by manthanank** [comment]
https://github.com/manthanank/blogs/blob/master/src%2Fpages%2Ftags%2F%5Btag%5D%2F%5Bpage%5D.astro

**Comment by satnaing** [comment]
Ugh!! the issue arises because `flatMap` doesn't work properly with async functions. Initially, `getPostsByTag` wasn't asynchronous, so it worked fine. However, since it now returns a promise, `flatMap` is causing issues.

To fix this, we need to update the getStaticPaths function as follows:

```ts
export async function getStaticPaths() {
  const posts = await getCollection("blog");

  const tags = getUniqueTags(posts);

  const paths = await Promise.all(
    tags.map(async ({ tag, tagName }) => {
      const tagPosts = await getPostsByTag(posts, tag);
      const totalPages = getPageNumbers(tagPosts.length);

      return totalPages.map(page => ({
        params: { tag, page: String(page) }, // Ensure page is a string
        props: { tag, tagName },
      }));
    })
  );

  return paths.flat(); // Flatten the array of arrays
}
```

**Comment by manthanank** [comment]
> Ugh!! the issue arises because `flatMap` doesn't work properly with async functions. Initially, `getPostsByTag` wasn't asynchronous, so it worked fine. However, since it now returns a promise, `flatMap` is causing issues.
> 
> To fix this, we need to update the getStaticPaths function as follows:
> 
> ```ts
> export async function getStaticPaths() {
>   const posts = await getCollection("blog");
> 
>   const tags = getUniqueTags(posts);
> 
>   const paths = await Promise.all(
>     tags.map(async ({ tag, tagName }) => {
>       const tagPosts = await getPostsByTag(posts, tag);
>       const totalPages = getPageNumbers(tagPosts.length);
> 
>       return totalPages.map(page => ({
>         params: { tag, page: String(page) }, // Ensure page is a string
>         props: { tag, tagName },
>       }));
>     })
>   );
> 
>   return paths.flat(); // Flatten the array of arrays
> }
> ```

Yes, I did it the same. But I did not pushed the code...

**Comment by manthanank** [comment]
It's working fine now.
