### ISSUE TITLE
Feature request: Add previous and next posts

### ISSUE THREAD

**Issue by vvep** [satnaing/astro-paper#358]
After reading a blog post, readers might leave the site immediately. To address this, consider adding recommendations for other posts, such as previous and next posts by date, or related posts at the bottom of a blog post. By providing these recommendations, the blog can encourage readers to stay longer, explore additional content, and potentially increase engagement and retention.

![Post recommendations](https://github.com/user-attachments/assets/9a107683-a628-49b8-8159-cbe88409b6e2)

**Comment by satnaing** [comment]
I just made a PR #372 for this feature.
You can give feedback, suggestions, or general comments on that.
After a while, I'll merge the PR.
Thanks.
