### ISSUE TITLE
Zoom post image on click

### ISSUE THREAD

**Issue by janbo208** [satnaing/astro-paper#36]
Hello,

I would like to be able to click on images in a blog post to show a zoomed in version. I often use wide images with lots of details that are easier to view when enlarged to take up the full width of the window.

**Comment by satnaing** [comment]
I believe you meant something like [Medium](https://medium.com/) does.
For that feature, I think we have to [integrate MDX](https://docs.astro.build/en/guides/integrations-guide/mdx/) for blog posts with custom image components. 
I'll consider adding MDX to AstroPaper. But I cannot guarantee when it will be integrated into AstroPaper. 
But, you can try on your own first if you want.

**Comment by janbo208** [comment]
Would it be possible to use the [medium-zoom](https://github.com/francoischalifour/medium-zoom) library for this feature?
I don't need to be able to enable this feature for single images, having it enabled for all images in blog posts would be enough for me.

 [Here](https://github.com/adityatelange/hugo-PaperMod/issues/384#issuecomment-899219940) is an example of it being used in a hugo theme, but I don't know how to make it work for this theme.

**Comment by satnaing** [comment]
Oh! I didn't know that exists.
I tested in my local and it works which might be exactly what you want.

First, install medium zoom
```
npm install medium-zoom
# or
yarn add medium-zoom
```

Then, add the following JS code just below `</style>` tag inside `PostDetails.astro`
```html
<script>
  import mediumZoom from "medium-zoom";

  mediumZoom(".prose img", {
    margin: 24,
    background: "rgba(0,0,0,0.9)",
    scrollOffset: 0,
  });
</script>
```

Note that you can tweak the option according to your needs.

**Comment by janbo208** [comment]
Thanks so much, works perfectly. 👍

**Comment by HenestrosaConH** [comment]
How would this be possible for Astro v3 with ViewTransitions? I've been trying to figure it out with no luck as it only seems to work when the page is refreshed.
