### ISSUE TITLE
"Tag" button not completely underlined

### ISSUE THREAD

**Issue by ShridiptaSatpati** [satnaing/astro-paper#387]
![image](https://github.com/user-attachments/assets/73d9d422-db29-4252-b91b-04d91bb96c75)

Whenever I try to create a site using this template the tag is always having a gap in the underline. Same problem whether I run it in localhost or in Netlify. I tried to view the site using different browsers and devices but the problem remained. I am a beginner, how to revolve this issue?

**Comment by patrick-kot** [comment]
Tailwind config, Its a personal choice/taste. But you can upper the underline offset in `src\components\Header.astro`.
Modify 
```css
...
  nav a.active {
    @apply underline decoration-wavy decoration-2 underline-offset-4;
  }
...
```
to
```css
...
  nav a.active {
    @apply underline decoration-wavy decoration-2 underline-offset-8;
  }
...
```
or
```css
...
  nav a.active {
    @apply underline decoration-wavy decoration-2 underline-offset-[5px];
  }
...
```
