### ISSUE TITLE
Post in the future is not appearing

### ISSUE THREAD

**Issue by eerison** [satnaing/astro-paper#395]
Hello guys :)

I was on version `4.5.0` and when I create a post with creation data in the future it was still displaying.
But after update to `4.5.1` the post does not appear anymore, just if I change the creation date for the past.

then I just want to make sure if it is a bug or a feature 😄

**Comment by satnaing** [comment]
Hello @eerison 

Posts with future dates should not appear in `prod` build.
So, this behavior is intentional. 😅

I'll close this issue for now.
Let me know if you have any other issues. Thanks.
