### ISSUE TITLE
Convert SVG generated previews to PNG

### ISSUE THREAD

**Issue by SeryiBaran** [satnaing/astro-paper#40]
Hello!

I advise you to convert the generated previews from SVG to PNG, to bypass the OpenGraph SVG limitation.

Here is a link:
https://dev.to/anasrin/generate-image-from-html-using-satori-and-resvg-46j6

Solution to the problem `Error: R] No loader is configured for ".node" files` is here:
https://github.com/evanw/esbuild/issues/1051#issuecomment-1006992549

**Comment by satnaing** [comment]
@SeryiBaran 
Thanks for opening this issue and for your suggestions.
I just merge a PR that resolves this issue. I believe it solves the SVG limitation you mentioned. Cheers! ✌🏻
