### ISSUE TITLE
[Docs]: Estimated Reading Time documentation issue

### ISSUE THREAD

**Issue by druwadi** [satnaing/astro-paper#406]
**Describe the Issue**
I'm attempting to setup the Estimated Reading Time feature, and I'm running into an issue. I noticed in the documentation [here](https://github.com/satnaing/astro-paper/blob/main/src/content/blog/how-to-add-an-estimated-reading-time.md#access-reading-time-outside-of-postdetails-optional), the suggestion is to update the file at `src/pages/tags/[tag]/[page].astro` with an updated function for getStaticPaths. This suggests that you use the function in utils `getPageNumbers`. This looks like it used to be in the codebase but may have since been removed. Is there a better suggested way to approach implementing this feature with this removed or is the best path forward to pull the older file back into my local repository?

**Proposed Changes**
Update the docs to make it more clear, or provide a suggestion and I can make the pull request.

**Additional Context**
N/A

**Comment by hoangnguyen92dn** [comment]
Indeed. I was struggling with the issue on `src/pages/tags/[tag]/[page].astro`, here is the update on my end to make it works  with the latest version

```
export async function getStaticPaths({ paginate }: GetStaticPathsOptions) {
  const posts = await getCollection("blog");
  const tags = getUniqueTags(posts);

  // Apply Promise
  const paths = await Promise.all(tags.map(async ({ tag, tagName }) => {
    const tagPosts = await getPostsByTag(posts, tag);

    return paginate(tagPosts, {
      params: { tag },
      props: { tagName },
      pageSize: SITE.postPerPage,
    });
  }));

  return paths.flat();
}
```

**Comment by satnaing** [comment]
Yep, the blog post is a bit outdated and needs an update.
I'll update the post later.

Thanks for pointing this out.
