### ISSUE TITLE
'astro' type error in src/pages/[ogTitle].svg.ts

### ISSUE THREAD

**Issue by gianpaj** [satnaing/astro-paper#41]
> Cannot find module 'astro' or its corresponding type declarations.ts

<img width="879" alt="image" src="https://user-images.githubusercontent.com/899175/221354065-49bfdf2f-bd82-492c-8cb1-85dc62a49e88.png">

I'm not sure where that issue is. I believe I have very similar packages versions to what's on `master`
```
$ pnpm list
Legend: production dependency, optional only, dev only

@example/basics@0.0.1 /Users/gianpaj/github/escuela-dev/escuela.dev (PRIVATE)

dependencies:
@astrojs/mdx 0.17.2            @types/react 18.0.28           react-dom 18.2.0
@astrojs/react 2.0.2           @types/react-dom 18.0.11       satori 0.3.2
@astrojs/sitemap 1.1.0         astro 2.0.15                   tailwindcss 3.2.7
@astrojs/tailwind 3.0.1        flowbite 1.6.3
@tailwindcss/typography 0.5.9  react 18.2.0
```

BTW: the image is still generating correctly.

Similar/related type issue in `src/env.ts`:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/899175/221354200-778c6ba7-3f8a-488a-8e9a-eddb3f1cdff1.png">

**Comment by satnaing** [comment]
Hello @gianpaj,
Sorry for late reply since I'm away from code for some days.
I've tried to reproduce your issue using pnpm but it seems to be fine for me. I can build and run dev server without any issues.
Have you resolved this issue? 
How can I reproduce this?
