### ISSUE TITLE
[BUG]: Block Equation Color Rendering Issue Outside of Lists in AstroPaper

### ISSUE THREAD

**Issue by jonathanhu237** [satnaing/astro-paper#412]
**Describe the bug**
When using the AstroPaper theme with KaTeX for math formula rendering, block equations  outside of lists display a color rendering issue. Specifically, the color of these block equations does not adapt to the theme's color scheme (e.g., dark/light mode) and remains fixed at #374151. In contrast, block equations placed inside lists render correctly and respond to the theme's color changes.

**To Reproduce**

1. Create the project by running:
 ```bash
 npm create astro@latest -- --template satnaing/astro-paper
 ```
2. Add the LaTeX integration by following the [official tutorial.](https://astro-paper.pages.dev/posts/how-to-add-latex-equations-in-blog-posts/).
3. Create a new blog post with the following content to test block equation rendering:

```bash
---
author: author
pubDatetime: 2024-11-08T02:09:57.000+08:00
modDatetime:
title: LaTeX
featured: false
draft: true
tags:
  - LaTeX
description: LaTeX
---

Block Equation outside the list:

$$
\int\_{-\infty}^{\infty} e^{-x^2} dx = \sqrt{\pi}
$$

Block Equation inside the list:

1. $$
   \int_{-\infty}^{\infty} e^{-x^2} dx = \sqrt{\pi}
   $$
```

**Expected Behavior**
Both block equations (inside and outside of lists) should have consistent color rendering and should automatically adapt to the theme's color scheme (dark/light mode).

**Actual Behavior**
- Block equations outside of lists have a fixed color (#374151), which does not adapt to the dark or light theme.
- Block equations inside lists adapt to the theme’s color scheme as expected.

**Screenshots**
![image](https://github.com/user-attachments/assets/8988524a-87cf-4da0-8dcc-08e5ca54bece)
![image](https://github.com/user-attachments/assets/558d5d1a-21dd-4015-b9f0-5502caaf8211)

**Comment by jonathanhu237** [comment]
Using the browser's developer tools, I observed that block equations outside lists do not inherit certain CSS properties that are applied to those inside lists.

The figure below shows the CSS properties applied to a block equation within a list.
![equation-inside-list](https://github.com/user-attachments/assets/e7f32a53-5ac4-4205-9af2-1c4d2713aae2)

The figure below displays the properties for a block equation outside a list.
![equation-outside-list](https://github.com/user-attachments/assets/15fbfd28-ec2a-40cc-bc28-36aa503a31aa)

To temporarily address this issue, I added the following CSS:
```css
span.katex-display {
  @apply text-skin-base;
}
```

This fix forces the correct color on the block equation. However, I am not certain if this is the optimal solution or if it may introduce other styling issues. And advice on a more robust fix would be appreciated.

**Comment by xyzqm** [comment]
Just curious, where did you add this css? I'm putting it in base.css (I've tried both under @layer base and @layer components) but it doesn't seem to have any effect.

**Comment by knothhe** [comment]
@xyzqm You can put the following code into your `src/styles/base.css` which is in effect.

```css
  /* .katex-display */
  .prose .katex-display {
    @apply text-skin-base;
  }
```

**Comment by knothhe** [comment]
I tried to fix this and guess the reason is as follows.

Astro uses [tailwindlabs/tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography?tab=readme-ov-file) to style rich text content, which is usually converted from non-HTML formats.

Most of the content can be rendered correctly because these elements have clear semantics, such as links `<a>`, lists `<li>`, paragraphs `<p>`, typography will render these elements correctly and the complete list can be found on the typography GitHub homepage.

The issue lies with block equation, which is not wrapped by any semantic block. You can see the comparison between inline formulas and display formulas in the screenshot.

<img width="1191" alt="Image" src="https://github.com/user-attachments/assets/24c367b3-2f79-4579-8f5e-835ea52168b5" />

**Comment by knothhe** [comment]
After completing the analysis, I think this might be more universal.
```css
  .prose span {
    @apply text-skin-base
  }
```

**Comment by jiang-zhexin** [comment]
I recently tried migrating my blog to astro-paper, and after configuring it according to https://astro-paper.pages.dev/posts/how-to-add-latex-equations-in-blog-posts/, I encountered the same problem. Is there a solution?

**Comment by knothhe** [comment]
> I recently tried migrating my blog to astro-paper, and after configuring it according to https://astro-paper.pages.dev/posts/how-to-add-latex-equations-in-blog-posts/, I encountered the same problem. Is there a solution?

Add this to your `src/styles/typography.css`, and it should work.
```css
/* Katex text color */
.katex-display {
    @apply text-foreground;
}
```

like this:

```css
@layer base {
  /* ===== Override default Tailwind Typography styles ===== */
  .app-prose {
    @apply prose;

    /* Katex text color */
    .katex-display {
        @apply text-foreground;
    }
  }
}
```

**Comment by oranshea** [comment]
> > I recently tried migrating my blog to astro-paper, and after configuring it according to https://astro-paper.pages.dev/posts/how-to-add-latex-equations-in-blog-posts/, I encountered the same problem. Is there a solution?
> 
> Add this to your `src/styles/typography.css`, and it should work.
> 
> /* Katex text color */
> .katex-display {
>     @apply text-foreground;
> }
> like this:
> 
> @layer base {
>   /* ===== Override default Tailwind Typography styles ===== */
>   .app-prose {
>     @apply prose;
> 
>     /* Katex text color */
>     .katex-display {
>         @apply text-foreground;
>     }
>   }
> }

@knothhe This is indeed useful, but what puzzles me is that after running it once according to your solution, and then reverting to the official tutorial's setting, the previous rendering issue disappeared. I don't quite understand it. If you know the reason, please let me know.
