### ISSUE TITLE
Having issue with top bar

### ISSUE THREAD

**Issue by mailman-2097** [satnaing/astro-paper#45]
Hi Satnaing,

My site is live, but the top nav bar with the dark theme toggle and other nav links is not working on mobile web browsers for My Site.

Can you please advise on what I can do to triage this? 

https://www.nishad.link/

If you can help in any way would really appreciate.

regards
Nishad

**Comment by mailman-2097** [comment]
The issue is with the blog heading text overlapping with the hamburger menu in portrait mode. there is no problem in landscape.

For now I will reduce the text size of the 

![image](https://user-images.githubusercontent.com/13964689/223896830-51873ff8-4dde-4b1c-9f8c-1d238a6fdf39.png)

**Comment by satnaing** [comment]
In your specific case, adding these classes in the Header would fix the problem.

file: `src/components/Header.astro`
```astro
<style>
  /* other styles */
  .logo {
    @apply absolute py-1 text-xl font-semibold sm:static sm:text-2xl sm:max-w-none top-0 max-w-[63%];
  }
  /* --- */
</style>
```
So, the newly added classes would be `sm:max-w-none top-0 max-w-[63%]`.

**Comment by mailman-2097** [comment]
Many thanks for your response.
