### ISSUE TITLE
How to add new post easily

### ISSUE THREAD

**Issue by universeroc** [satnaing/astro-paper#53]
Firstly thank you for astro-paper, it' great and amazing simple and powerful for me to build my personal blog!

I'm the user of jekyll and octopress, octopress has a cli command to create new post:

```bash
octopress new "hello the article title"
```

It creates the markdown format post under _posts directory and convert the title " " into "-" besides the default template is filled the title and timestamp and default layout etc.

It's easy to add new posts and I'm sorry that I did not find the alternative command to implement the same operation, can you help me whether there already is or not ? How to make it?

**Comment by janik6n** [comment]
I just migrated my blog to use this awesome template, and I am in the process of writing a new article scaffolding tool, which Ii intent to publish on npm. I will ping you you here, when this will be ready to test (most likely later today).

**Comment by baddate** [comment]
using this bash script
```bash
#!/bin/bash

if [[ $# > 1 ]]; then
  echo "one argument is allowed: file name"
  exit
fi

if [[ -z $1 ]]; then
  fname="a-TEMPLATE-post"
else
  fname=$(basename "$1")
fi


time=$(date +"%Y-%m-%dT%T%:z")

frontmatter=$(cat << EOM
---
title: ""
postSlug: $(basename $1)
description: ""
pubDatetime: $time
tags:
  - 
author: YOURNAME #change it
ogImage: ""
featured: false
draft: false
---
EOM
)

markdown="${frontmatter}

"

echo "$markdown" > $fname.md

echo "Markdown file generated！"
```
save it as a `.sh` file.
usage:
executing it at project root directory or anywhere.
```bash

bash file_generator.sh src/content./blog/new-post-name-without-filetype
```
it will generate a new markdown file with default frontmatters.

**Comment by universeroc** [comment]
> using this bash script
> 
> ```shell
> #!/bin/bash
> 
> if [[ $# > 1 ]]; then
>   echo "one argument is allowed: file name"
>   exit
> fi
> 
> if [[ -z $1 ]]; then
>   fname="a-TEMPLATE-post"
> else
>   fname=$(basename "$1")
> fi
> 
> 
> time=$(date +"%Y-%m-%dT%T%:z")
> 
> frontmatter=$(cat << EOM
> ---
> title: ""
> postSlug: $(basename $1)
> description: ""
> pubDatetime: $time
> tags:
>   - 
> author: YOURNAME #change it
> ogImage: ""
> featured: false
> draft: false
> ---
> EOM
> )
> 
> markdown="${frontmatter}
> 
> "
> 
> echo "$markdown" > $fname.md
> 
> echo "Markdown file generated！"
> ```
> 
> save it as a `.sh` file. usage: executing it at project root directory or anywhere.
> 
> ```shell
> bash file_generator.sh src/content./blog/new-post-name-without-filetype
> ```
> 
> it will generate a new markdown file with default frontmatters.

Thanks for your solution, and I've already given one in #54
