### ISSUE TITLE
missing tailwindcss dependency?

### ISSUE THREAD

**Issue by mikelehen** [satnaing/astro-paper#6]
After running:

```
yarn create astro -- --template satnaing/astro-paper
yarn
yarn dev
```
I got:
>  error   Cannot find package 'tailwindcss' imported from /Users/mikelehen/src/vanny-the-van/node_modules/@astrojs/tailwind/dist/index.js

Running `yarn add tailwindcss` seems to have fixed the issue.

**Comment by satnaing** [comment]
Yep.
Prior to `@astrojs/tailwind v2.0.0`, tailwindcss wasn't required as a peer dependency. Some days ago, I updated `@astrojs/tailwind` without installing Tailwind as a peer dep. Then I tested with `npm` and it was working fine. 
But as you mentioned, trying out using `yarn` seems to have a problem.

I'll update it.
Thank you @mikelehen for pointing this out.

**Comment by mikelehen** [comment]
Awesome, thank you!
