### ISSUE TITLE
how to update astro paper?

### ISSUE THREAD

**Issue by hassam7** [satnaing/astro-paper#68]
Hi, is their any official guide on updating the astro paper?

**Comment by satnaing** [comment]
I usually update AstroPaper using [ncu](https://www.npmjs.com/package/npm-check-updates). For breaking changes, I have to manually check some features. 
I'll write a docs post for this in the future. 
Thanks.

**Comment by eerison** [comment]
But will it work if I make changes?

**Comment by satnaing** [comment]
@eerison 
Sure, if you only update the dependencies of the project, it will still work as long as your updated dependencies are not major updates.
I wrote an article for this issue and I'll push it in a sec. You can also check that blog post.

**Comment by eerison** [comment]
could you add the post here please

**Comment by satnaing** [comment]
Hope it works. @everyone

If you still have some problems, plz do let me know. ✌🏻
