### ISSUE TITLE
Unable to build on netlify due to some resvg-js issues

### ISSUE THREAD

**Issue by antoniods** [satnaing/astro-paper#75]
As the title says, I work with netlify and resvg-js causes problems during the "build" stage.
It's currently impossible to use netlify's continuos deployement because of this issue.

**Comment by MrGKanev** [comment]
Can you provide the issue, so we can try to help? - I'm using Netlify myself and don't have any issues with it.

**Comment by antoniods** [comment]
My issue here : [](https://github.com/yisibl/resvg-js/issues/175 )

**Comment by antoniods** [comment]
My issue here : [https://github.com/yisibl/resvg-js/issues/175](https://github.com/yisibl/resvg-js/issues/175)

**Comment by satnaing** [comment]
Hello @antoniods ,
Sry for my late reply.
Do you still have that problem? Are you able to solve that? Plz let me know.

**Comment by antoniods** [comment]
Hi @satnaing, I still have the problem on Netifly but not on Vercel. So i solved moving to the second one ...

**Comment by satnaing** [comment]
Close this one for now.
You can reopen this if you still have some issues.
