### ISSUE TITLE
I was trying to add new react component with custom css but in the output I did not see any custom css. Default CSS get applied.

### ISSUE THREAD

**Issue by anurag629** [satnaing/astro-paper#87]
How to fix this?

**Comment by anurag629** [comment]
Thanks @jbrr, I will try this.

**Comment by satnaing** [comment]
Hello @anurag629 
Sorry for my late response. 
Are you still facing the issue? Did you already solve it?

**Comment by satnaing** [comment]
I'll close this issue for now.
You can reopen this if you still have some issue. Thanks.
