### ISSUE TITLE
Incorrect use of   "canonical meta tag"

### ISSUE THREAD

**Issue by FredySandoval** [satnaing/astro-paper#95]
in /src/layouts/Layout.astro line 48 <code>\<meta property="og:url" content={canonicalURL} /></code> this will add the same canonical tag to every page

The use of the "rel=canonical" link element is specifically intended for specifying a preferred canonical URL for duplicate or similar pages. It is not necessary for pages that do not have duplicate content or similar versions.

It's important to use the "rel=canonical" link annotation judiciously and only when it's necessary. Adding the canonical tag to every page, even when it's not needed, can lead to confusion and incorrect signals to search engines, potentially affecting your website's search rankings.

**Comment by satnaing** [comment]
Thank you for bringing up this concern about the use of "canonical URL".
If you have any further suggestions or concerns, please feel free to share them. 

Also, if you want to make a PR for this issue, let me know. If not, I'll make the necessary adjustments accordingly.

**Comment by r0hitm** [comment]
As per [RFC 6596](https://www.rfc-editor.org/rfc/rfc6596#section-3):

> The target (canonical) IRI MAY:
> ...
> Be self-referential (context IRI identical to target IRI).

So, using "rel=canonical" is not a problem on every page
