### ISSUE TITLE
Suggestion: Use ViewTransitions

### ISSUE THREAD

**Issue by agriffard** [satnaing/astro-paper#96]
Do you plan to use ViewTransitions https://astro.build/blog/astro-290/?
Or, may be, you will wait until it is not experimental anymore in 3.0?

**Comment by satnaing** [comment]
Yep, I might include it when upgrading AstroPaper to Astro v3, but for now, I'm not planning to use this feature yet.

**Comment by tanishqmanuja** [comment]
Is there a reason for card and datetime components are react comps and not astro comps, bc i can't find a way to add transition:name in react components.

**Comment by satnaing** [comment]
> Is there a reason for card and datetime components to be react components and not astro components, bc i can't find a way to add transition:name in react components.

@tanishqmanuja 
Yes. These components are also used inside `search` which needs to be React component for interactivity. But in AstroPaper v3, I've tried to solve this issue by separating Astro component and React component with minimal duplicate codes.

**Comment by tanishqmanuja** [comment]
Btw if we are not using react-dom, migration to preact will save a lot of bundle size. What's your opinion, could there be any problem that i am unaware of?
