### ISSUE TITLE
When site title contains a space, a line break is made

### ISSUE THREAD

**Issue by PNRYates** [satnaing/astro-paper#97]
![image](https://github.com/satnaing/astro-paper/assets/89813543/e8b549b4-f62e-4187-880a-976fe79b332f)

This might be a dumb question, but I can't seem to figure out how to remove the line break in the site title. the 'title' (in config.ts) is set to `Peter Yates`.

**Comment by satnaing** [comment]
Hello @PNRYates, 
Sorry for my late reply. You might already have solved this issue. 
However, just in case, here is the solution

file: src/components/Header.astro
```html
<!-- other codes -->
    <div class="top-nav-wrap">
      <a href="/" class="logo whitespace-nowrap"> 👈🏻
<!-- other codes -->
```

All you have to do is adding `whitespace-nowrap` class in the logo element.
